Reviews\DefaultBundle\Entity\AclSecurityIdentities:
    type: entity
    table: acl_security_identities
    uniqueConstraints:
        UNIQ_8835EE78772E836AF85E0677:
            columns:
                - identifier
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        identifier:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        username:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
