Reviews\DefaultBundle\Entity\MediaGalleryMedia:
    type: entity
    table: media__gallery_media
    indexes:
        IDX_80D4C5414E7AF8F:
            columns:
                - gallery_id
        IDX_80D4C541EA9FDD75:
            columns:
                - media_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: integer
            nullable: false
            options:
                unsigned: false
        enabled:
            type: boolean
            nullable: false
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        gallery:
            targetEntity: MediaGallery
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gallery_id:
                    referencedColumnName: id
            orphanRemoval: false
        media:
            targetEntity: MediaMedia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                media_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
