Reviews\DefaultBundle\Entity\MediaGallery:
    type: entity
    table: media__gallery
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        context:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        defaultFormat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: default_format
        enabled:
            type: boolean
            nullable: false
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
