Reviews\DefaultBundle\Entity\Products:
    type: entity
    table: products
    repositoryClass: Reviews\DefaultBundle\Repositories\Database\Products
    indexes:
        class1_FK_idx:
            columns:
                - class1
        class2_FK_idx:
            columns:
                - class2
        class3_FK_idx:
            columns:
                - class3
        manufacturers_FK_idx:
            columns:
                - manufacturer_id
        products_similarity:
            columns: [similarity_hash]
        products_name:
            columns: [name]
        products_class1:
            columns: [class1]
        products_rating:
            columns: [rating]
    id:
        productId:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
            id: true
            column: product_id

    fields:
        code:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        added:
            type: datetime
            nullable: false
        deleted:
            type: boolean
            nullable: false
        similarityHash:
            type: bigint
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: similarity_hash
        rating:
            type: decimal
            nullable: true
            options:
                unsigned: true
                default: '0'
            column: rating
    oneToMany:
        productDetails:
            targetEntity: Reviews\DefaultBundle\Entity\SitesProductsDetails
            cascade: ["persist", "remove"]
            mappedBy: product
        images:
            targetEntity: Reviews\DefaultBundle\Entity\ProductImages
            mappedBy: product
            cascade: ["persist", "remove"]
        properties:
            targetEntity: Reviews\DefaultBundle\Entity\Properties
            mappedBy: product
            cascade: ["persist", "remove"]
        reviews:
            targetEntity: Reviews\DefaultBundle\Entity\Reviews
            mappedBy: product
            cascade: ["persist", "remove"]
    manyToOne:
        manufacturer:
            targetEntity: Manufacturers
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manufacturer_id:
                    referencedColumnName: manufacturer_id
            orphanRemoval: false
        class1:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                class1:
                    referencedColumnName: category_id
            orphanRemoval: false
        class2:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                class2:
                    referencedColumnName: category_id
            orphanRemoval: false
        class3:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                class3:
                    referencedColumnName: category_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
