Reviews\DefaultBundle\Entity\Reviews:
    type: entity
    table: reviews
    id:
        review_id:
            type: integer
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        review:
            type: text
            nullable: true
        rating:
            type: integer
            nullable: true
        added:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        product:
            targetEntity: Reviews\DefaultBundle\Entity\Products
            inversedBy: reviews
            joinColumn:
                name: product_id
                referencedColumnName: product_id
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: reviews
            joinColumn:
                name: user_id
                referencedColumnName: id