Reviews\DefaultBundle\Entity\Sites:
    type: entity
    table: sites
    id:
        siteId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: site_id
            generator:
                strategy: IDENTITY
    fields:
        baseUrl:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: base_url
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
