reviews_similarity_homepage:
    path:     /similarity
    defaults: { _controller: ReviewsSimilarityBundle:Default:index }
reviews_similarity_update-database:
    path:     /update-database
    defaults: { _controller: ReviewsSimilarityBundle:Default:updateDatabase }
reviews_similarity_find-similarities:
    path:     /find-similarities
    defaults: { _controller: ReviewsSimilarityBundle:Default:findSimilarities }