SVM:
    directory: "/Resources/data/classifier-models/"
    filename: "model-svm.svm"

Bayes:
    directory: "%s/Resources/data/classifier-models/"
    filename: "model-bayes.txt"

Stemmer:
    language: "romanian"