services:
#    reviews_predict.example:
#        class: Reviews\PredictBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     cache:
         class: Doctrine\Common\Cache\ApcCache