reviews_similarity:
    resource: "@ReviewsSimilarityBundle/Resources/config/routing.yml"
    prefix:   /

reviews_predict:
    resource: "@ReviewsPredictBundle/Resources/config/routing.yml"
    prefix:   /

reviews_default:
    resource: "@ReviewsDefaultBundle/Resources/config/routing.yml"
    prefix:   /

reviews_parser:
    resource: "@ReviewsParserBundle/Resources/config/routing.yml"
    prefix:   /

#admin_override:
#    resource: "@AdminOverrideBundle/Resources/config/routing.yml"
#    prefix:   /

framework_extension:
    resource: "@FrameworkExtensionBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

#admin_area:
#    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
#    prefix: /admin

#_sonata_admin:
#  resource: .
#  type: sonata_admin
#  prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Liip imagine bundle routing
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"