# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    app.form.registration:
#           class: Tutorials\BaseBundle\Form\Registration
#           tags:
#               - { name: form.type, alias: tutorials_user_registration }
#    app.form.profile.edit.profile:
#           class: Tutorials\BaseBundle\Form\EditProfileType
#           tags:
#               - { name: form.type, alias: tutorials_user_edit_profile }
#    app.form.user.resetting:
#           class: Tutorials\BaseBundle\Form\ResettingPasswordType
#           tags:
#               - { name: form.type, alias: tutorials_user_resetting }