Reviews\SimilarityBundle\Entity\ProductsImages:
    type: entity
    table: products_images
    indexes:
        products_FK_idx:
            columns:
                - product_id
    id:
        productImageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: product_image_id
            generator:
                strategy: IDENTITY
    fields:
        overlayUrl:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: overlay_url
        thumbnailUrl:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: thumbnail_url
        added:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        product:
            targetEntity: Products
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: product_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
