UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        birthday:
            type: datetime
            nullable: true

        avatarUrl:
            type: string
            nullable: true
    oneToMany:
        reviews:
            targetEntity: Reviews\DefaultBundle\Entity\Reviews
            mappedBy: user
        products:
            targetEntity: Reviews\DefaultBundle\Entity\SitesProductsDetails
            mappedBy: user