reviews_default_homepage:
    path:     /
    defaults: { _controller: ReviewsDefaultBundle:Default:index }
reviews_add_Product:
    path:     /add-product
    defaults: { _controller: ReviewsDefaultBundle:Default:addProduct}
reviews_all_products:
    path: /products/{page}/{category}
    defaults: { _controller: ReviewsDefaultBundle:Default:index, page: 1, category: 0}