services:
    sonata.block.service.categories:
            class: Reviews\DefaultBundle\SonataBlocks\Service\Categories
            arguments:
                - sonata.block.service.categories
                - "@templating"
                - "@doctrine"
            tags:
                - { name: sonata.block }
    products:
            class: Reviews\DefaultBundle\Services\Products
            arguments:
                - '@doctrine'
