services:
    sonata.block.service.categories:
            class: Reviews\DefaultBundle\SonataBlocks\Service\Categories
            arguments:
                - sonata.block.service.categories
                - "@templating"
                - "@doctrine"
            tags:
                - { name: sonata.block }
    products:
            class: Reviews\DefaultBundle\Services\Products
            arguments:
                - '@doctrine'
    products_admin:
            class: Reviews\DefaultBundle\Admin\ProductsAdmin
            arguments:
              - ~
              - Reviews\DefaultBundle\Entity\Products
              - ~
            tags:
              - { name: sonata.admin, manager_type: orm, label: "Products", group: "Products" }
            calls:
              - [setTranslationDomain, [admin]]
              - [addChild, [@review_admin]]

    review_admin:
            class: Reviews\DefaultBundle\Admin\ReviewsAdmin
            arguments:
                - ~
                - Reviews\DefaultBundle\Entity\Reviews
                - ~
            tags:
              - { name: sonata.admin, manager_type: orm, label: "Reviews", group: "Reviews", show_in_dashboard: false }
